#!/bin/bash

# Depends on: aspell 
Description="Russian dictionaries for Aspell"
url="http://aspell.net"
Packager="cdrw"

name=aspell6-ru
version=0.99f7-1
release=1

source=(ftp://ftp.gnu.org/gnu/aspell/dict/ru/$name-$version.tar.bz2)

build() {
        cd aspell6-ru*
        
	./configure
	
        make
        make DESTDIR=$PKG install
}
  
