#!/bin/sh

# Depends on: libnatspec nasm yasm
Description="Command-line version of the 7zip compressed file archiver,based on libnatspec patch"
url=http://p7zip.sourceforge.net
Packager=cdrw

name=p7zip
version=16.02
release=1

source=(http://downloads.sourceforge.net/sourceforge/$name/${name}_${version}_src_all.tar.bz2
        https://raw.githubusercontent.com/buzztaiki/pkgbuild-p7zip-natspec/master/CVE-2016-9296.patch
        https://raw.githubusercontent.com/buzztaiki/pkgbuild-p7zip-natspec/master/natspec.patch)

build() {
	cd ${name}_$version

	patch -p1 < ../natspec.patch || exit 1
	patch -Np1 < ../CVE-2016-9296.patch || exit 1

	[[ `uname -m` = x86_64 ]] \
	&& cp makefile.linux_amd64_asm makefile.machine \
	|| cp makefile.linux_x86_asm_gcc_4.X makefile.machine
	make -j1 all3 OPTFLAGS="${CXXFLAGS}"
	make install DEST_DIR=$PKG DEST_HOME=/usr DEST_MAN=/usr/share/man

}
