#!/bin/bash 

# Depends on: glib gtk3 openconnect
description="GTK GUI for ConnMan"
packager="cdrw"
url="https://github.com/jgke/connman-gtk"

name=connman-gtk
version=1.1.1
release=1

source=(${url}/releases/download/v${version}/$name-$version.tar.bz2)

build() {

        cd $name-$version

	./configure                         \
		   --bindir=/usr/bin        \
		   --datarootdir=/usr/share \
		   --mandir=/usr/share/man  \
		   --with-openconnect=dynamic

        make
        make DESTDIR=$PKG install

}
