#!/bin/bash

# Depends on: unzip libgsf libreoffice
description="thumbnailer for LibreOffice, OpenOffice.org and Microsoft Office files"
packager="cdrw"
url="https://launchpad.net/ooo-thumbnailer"
CWD=`pwd`
name=ooo-thumbnailer
version=0.5
release=1

source=(https://launchpadlibrarian.net/84957712/ooo-thumbnailer-0.5.tar.gz)

build() {
	unzip $CWD/ooo-thumb-man.zip -d $SRC

	cd $name-$version

	install -Dm755 $name                          "${PKG}/usr/bin/$name"
	install -Dm644 gsf-office-thumbnailer.schemas "${PKG}/usr/share/gconf/gsf-office-thumbnailer.schemas"
	install -Dm644 ooo-thumbnailer.schemas        "${PKG}/usr/share/gconf/ooo-thumbnailer.schemas"
	install -Dm644 $name.thumbnailer              "${PKG}/usr/share/thumbnailers/$name.thumbnailer"
	install -Dm644 ../$name.1                     "${PKG}/usr/share/man/man1/$name.1"

cat > ${PKG}/usr/share/thumbnailers/$name.thumbnailer << EOF
[Thumbnailer Entry]
TryExec=ooo-thumbnailer
Exec=/usr/bin/ooo-thumbnailer %i %o %s
MimeType=application/vnd.oasis.opendocument.graphics;application/vnd.oasis.opendocument.presentation;application/vnd.oasis.opendocument.spreadsheet;application/vnd.oasis.opendocument.text;
EOF

}
