#!/bin/bash

# Depends on: gtk2
description="gtkdialog (GTK2 UI builder)"
packager="cdrw"
url="https://github.com/oshazard/gtkdialog"

name=gtkdialog
version=0.8.3
release=1

source=(https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/$name/$name-$version.tar.gz)

build() {

        cd $name-$version
        ./configure --prefix=/usr            \
                    --mandir=/usr/share/info \

        make
        make DESTDIR=$PKG install

}
