#!/bin/bash 

# Depends on: cmake freeglut
description="bullet (physics library)"
packager="cdrw"
url="https://github.com/bulletphysics"

name=bullet
version=2.87
release=1

source=(https://github.com/bulletphysics/bullet3/archive/${version}.tar.gz)

build() {

        cd ${name}3-$version

        cmake                            \
             -DCMAKE_INSTALL_PREFIX=/usr \
             -DBUILD_SHARED_LIBS=ON      \
             -DBUILD_CPU_DEMOS=OFF       \
             -DBUILD_DEMOS=OFF           \
             -DINSTALL_LIBS=ON           \
             -DINSTALL_EXTRA_LIBS=ON .

        make
        make DESTDIR=$PKG install

}
