#!/bin/bash

# Depends on: unzip
description="unace (a decompression tool for ACE archives)"
packager="cdrw"
url="http://www.winace.com/"
CWD=`pwd`
name=unace
version=2.5
release=1

source=(http://ftp.riken.jp/Linux/debian/debian/pool/non-free/u/unace-nonfree/$name-nonfree_${version}.orig.tar.gz)

build() {
        unzip $CWD/unace_patches.zip -d $SRC

        cd $name-$version

        for i in $( cat ../series ); do
             patch -p1 < ../$i
        done

        make

        install -Dm755 $name       "${PKG}/usr/bin/unace"
        install -Dm644 ../$name.1  "${PKG}/usr/share/man/man1/rar.1"

}
