#!/bin/bash 

# Depends on: glib libxml2 gsl gobject-introspection
description="GStreamer v1.x (streaming multimedia framework)"
packager="cdrw"
url="http://gstreamer.freedesktop.org/src/gstreamer/gstreamer-$version.tar.xz"

name=gstreamer1
version=1.10.2
release=1

source=(http://gstreamer.freedesktop.org/src/gstreamer/gstreamer-$version.tar.xz)

build() {

        cd gstreamer-$version
	
        ./configure                                              \
	           --prefix=/usr                                 \
                   --with-package-name="GStreamer $version BLFS" \
                   --with-package-origin="http://www.linuxfromscratch.org/blfs/view/svn/"
        make
        make DESTDIR=$PKG install

}
