#!/bin/bash

# Depends on: cython libcompizconfig
description="compizconfig-python (Python bindings for compiz config)"
packager="cdrw"
url="https://github.com/raveit65/compizconfig-python"

name=compizconfig-python
version=0.8.14
release=1

source=(https://github.com/compiz-reloaded/compizconfig-python/releases/download/v0.8.14/$name-$version.tar.xz)

build() {

        cd $name-$version
        ./configure --prefix=/usr           \
                    --sysconfdir=/etc       \
                    --localstatedir=/var    \
                    --enable-static=no      \
                    --docdir=/usr/share/doc/$name-$version
        make
        make DESTDIR=$PKG install

}
